# Generated by Django 3.0.5 on 2021-02-26 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20210226_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('genre__slug', 'year')},
        ),
    ]
