# Generated by Django 3.0.5 on 2021-02-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210226_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('category__slug', 'year', 'name')},
        ),
    ]
