# Generated by Django 3.0.5 on 2021-02-26 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_auto_20210226_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
